// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/ruromero/presentations/restaurant-operator/pkg/apis/restaurant/v1alpha1.Restaurant":       schema_pkg_apis_restaurant_v1alpha1_Restaurant(ref),
		"github.com/ruromero/presentations/restaurant-operator/pkg/apis/restaurant/v1alpha1.RestaurantSpec":   schema_pkg_apis_restaurant_v1alpha1_RestaurantSpec(ref),
		"github.com/ruromero/presentations/restaurant-operator/pkg/apis/restaurant/v1alpha1.RestaurantStatus": schema_pkg_apis_restaurant_v1alpha1_RestaurantStatus(ref),
	}
}

func schema_pkg_apis_restaurant_v1alpha1_Restaurant(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Restaurant is the Schema for the restaurants API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/ruromero/presentations/restaurant-operator/pkg/apis/restaurant/v1alpha1.RestaurantSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/ruromero/presentations/restaurant-operator/pkg/apis/restaurant/v1alpha1.RestaurantStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/ruromero/presentations/restaurant-operator/pkg/apis/restaurant/v1alpha1.RestaurantSpec", "github.com/ruromero/presentations/restaurant-operator/pkg/apis/restaurant/v1alpha1.RestaurantStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_restaurant_v1alpha1_RestaurantSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "RestaurantSpec defines the desired state of Restaurant",
				Properties: map[string]spec.Schema{
					"info": {
						SchemaProps: spec.SchemaProps{
							Description: "INSERT ADDITIONAL SPEC FIELDS - desired state of cluster Important: Run \"operator-sdk generate k8s\" to regenerate code after modifying this file Add custom validation using kubebuilder tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html",
							Ref:         ref("github.com/ruromero/presentations/restaurant-operator/pkg/apis/restaurant/v1alpha1.Info"),
						},
					},
					"menu": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/ruromero/presentations/restaurant-operator/pkg/apis/restaurant/v1alpha1.Menu"),
						},
					},
					"deployment": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/ruromero/presentations/restaurant-operator/pkg/apis/restaurant/v1alpha1.DeploymentSpec"),
						},
					},
				},
				Required: []string{"info", "menu"},
			},
		},
		Dependencies: []string{
			"github.com/ruromero/presentations/restaurant-operator/pkg/apis/restaurant/v1alpha1.DeploymentSpec", "github.com/ruromero/presentations/restaurant-operator/pkg/apis/restaurant/v1alpha1.Info", "github.com/ruromero/presentations/restaurant-operator/pkg/apis/restaurant/v1alpha1.Menu"},
	}
}

func schema_pkg_apis_restaurant_v1alpha1_RestaurantStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "RestaurantStatus defines the observed state of Restaurant",
				Properties: map[string]spec.Schema{
					"host": {
						SchemaProps: spec.SchemaProps{
							Type:   []string{"string"},
							Format: "",
						},
					},
				},
			},
		},
		Dependencies: []string{},
	}
}
