apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"restaurant.ruben.redhat.com/v1alpha1","kind":"Restaurant","metadata":{"name":"los-pipos"},"spec":{"contact":"958
      28 47 10","foodType":"Tapas bar","location":"Granada","menu":{"desserts":[{"descrption":"Y
      canela","name":"Arroz con leche","price":2},{"description":"Dulce tradicional
      granadino","name":"Piononos","price":4}],"main":[{"description":"Revuelto de
      chopitos, puntillitas, calamares y pescado de temporada","name":"Fritura de
      pescado","price":10},{"description":"De harina con sardinas y tomates secos","name":"Migas","price":9},{"description":"Papas
      a lo pobre con pimientos, chorizo, morcilla y huevos fritos","name":"Plato alpujarreño","price":11.2}],"starters":[{"description":"La
      ensalada que te gusta pero con aguacate y piña","name":"Ensalada tropical","price":8},{"description":"Caseras
      y de jamón serrano","name":"Croquetas","price":7},{"description":"Muy crujientes
      y con miel de caña","name":"Berenjenas fritas","price":8}]},"name":"Mesón Los
      Pipos"}}]'
    capabilities: Basic Install
  name: restaurant-operator.v0.1.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Restaurant
      name: restaurants.restaurant.ruben.redhat.com
      version: v1alpha1
  description: Placeholder description
  displayName: Restaurant Operator
  install:
    spec:
      deployments:
      - name: restaurant-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: restaurant-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: restaurant-operator
            spec:
              containers:
              - command:
                - restaurant-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: restaurant-operator
                image: REPLACE_IMAGE
                imagePullPolicy: Always
                name: restaurant-operator
                resources: {}
              serviceAccountName: restaurant-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - apps
          resourceNames:
          - restaurant-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - restaurant.ruben.redhat.com
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: restaurant-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.1.0
